apiVersion: apps/v1
kind: Deployment
metadata:
  name: boarddb
  labels:
    app: boarddb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boarddb
  template:
    metadata:
      labels:
        app: boarddb
    spec:
      containers:
      - name: boarddb
        image: lexicon420/boarddb
        env:
        - name: authURL
            valueFrom:
              secretKeyRef:
                name: secrets
                key: authURL 
        - name: mqURL
            valueFrom:
              secretKeyRef:
                name: secrets
                key: mqURL  
        - name: ContactPoint
            valueFrom:
              secretKeyRef:
                name: secrets
                key: ContactPoint
        - name: CPort
            valueFrom:
              secretKeyRef:
                name: secrets
                key: CPort
        - name: CName
            valueFrom:
              secretKeyRef:
                name: secrets
                key: CName
        - name: CPW
            valueFrom:
              secretKeyRef:
                name: secrets
                key: CPW
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: boarddb-service
spec:
  selector:
    app: boarddb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
