apiVersion: apps/v1
kind: Deployment
metadata:  
    name: boardauth
spec:  
    replicas: 1
    selector:    
        matchLabels:      
          app: boardauth 
    template:    
        metadata:      
          labels:        
            app: boardauth    
        spec:      
          containers:      
          - name: boardauth        
            image: lexicon420/board-auth        
            imagePullPolicy: IfNotPresent        
            env:          
              - name:  PORT            
                value: "7248"        
            resources:          
              limits:            
                memory: "64Mi"            
                cpu: "128m"        
            ports:        
            - containerPort: 7248          
              name: http 
---
apiVersion: v1
kind: Service
metadata:  
   name: boardauth
spec:  
   selector:    
      app: boardauth
   ports:  
   - port: 80    
