apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: lexicon420/api-gateway:loadtest
        imagePullPolicy: Always
        env:
        - name: "CorsOrigin"
            valueFrom:
              secretKeyRef:
                name: secrets
                key: CorsOrigin
        - name: "auth0Domain"
            valueFrom:
              secretKeyRef:
                name: secrets
                key: auth0Domain
        - name: "auth0Audience"
            valueFrom:
              secretKeyRef:
                name: secrets
                key: auth0Audience
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 1024Mi
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
